server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: bachir
    password: password
    url: jdbc:postgresql://postgres2:5432/fraud
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true  # This is by default true
    register-with-eureka: true # This is by default true
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId}:-}, %X{spanId:-}]'
